hex_literal_case = "Lower"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
merge_derives = true

format_code_in_doc_comments = true
wrap_comments = true
